---

# Supporting containers

- name: Run the cache service
  docker_container:
    name: cache
    image: redis:5
    pull: yes
    hostname: cache
    restart_policy: always
    networks:
      - name: opennotificaties
    purge_networks: yes
    networks_cli_compatible: yes

- name: Run the RabbitMQ message broker
  docker_container:
    name: message-broker
    image: rabbitmq:3.7
    pull: yes
    hostname: message-broker
    restart_policy: always
    networks:
      - name: opennotificaties
    purge_networks: yes
    networks_cli_compatible: yes
    env:
      RABBITMQ_DEFAULT_USER: "{{ opennotificaties_rabbitmq_user }}"
      RABBITMQ_DEFAULT_PASS: "{{ opennotificaties_rabbitmq_pass }}"

# Application containers

- name: Run the Open Notificaties backend service
  docker_container:
    name: "{{ item.name }}"
    image: "{{ opennotificaties_image }}"
    pull: yes
    hostname: "{{ item.name }}"
    restart_policy: always
    state: started
    restart: "{{ opennotificaties_env_file_template.changed }}"
    networks:
      - name: opennotificaties
    purge_networks: yes
    networks_cli_compatible: yes
    volumes:
      - /var/run/postgresql:/var/run/postgresql
      - "{{ opennotificaties_env_file }}:/app/.env"
    ports:
      - "127.0.0.1:{{ item.port }}:8000"
    env:
      DB_HOST: "{{ opennotificaties_db_host }}"
      DB_PORT: "{{ opennotificaties_db_port | string }}"
      RABBITMQ_HOST: message-broker
      RABBITMQ_PORT: '5672'
      SECRET_KEY: "{{ opennotificaties_secret_key }}"
  with_items: "{{ opennotificaties_replicas }}"

- name: Run the Open Notificaties background workers
  docker_container:
    name: "{{ item.name }}"
    image: "{{ opennotificaties_image }}"
    pull: yes
    hostname: "{{ item.name }}"
    restart_policy: always
    state: started
    restart: "{{ opennotificaties_env_file_template.changed }}"
    networks:
      - name: opennotificaties
    purge_networks: yes
    networks_cli_compatible: yes
    volumes:
      - /var/run/postgresql:/var/run/postgresql
      - "{{ opennotificaties_env_file }}:/app/.env"
    env:
      DB_HOST: "{{ opennotificaties_db_host }}"
      DB_PORT: "{{ opennotificaties_db_port | string }}"
      RABBITMQ_HOST: message-broker
      RABBITMQ_PORT: '5672'
      SECRET_KEY: "{{ opennotificaties_secret_key }}"
    command: ["/celery_worker.sh"]
  with_items: "{{ opennotificaties_worker_replicas }}"
