---

- import_tasks: setup_env.yml

- import_tasks: dependencies.yml
# - import_tasks: docker-login.yml
- import_tasks: volumes.yml
- import_tasks: network.yml
- import_tasks: containers.yml

- import_tasks: set_facts.yml

# load the nginx template
- import_role:
    name: openzaak.deploy.open_zaak_nginx
