---

# Set up the environment files on the host machine
- name: Create application group
  group:
    name: openzaak

- name: Create application user
  user:
    name: openzaak
    group: openzaak
    comment: Application user
    create_home: yes
    state: present

- name: Setup the environment variables
  template:
    src: "{{ openzaak_env_template }}"
    dest: /home/openzaak/.env
    mode: 0400
    owner: "1000"
    group: "1000"    
  register: openzaak_env_file_template

- name: Ensure nginx user exists
  user:
    name: "{{ openzaak_nginx_user }}"
    groups: "1000"
    state: present

# /var/lib/docker/volumes is by default only enter-able by the root user. However,
# nginx on the host system serves the files for private media uploads, which runs as
# the nginx user.
# Therefore, we change the group of /var/lib/docker/volumes to add the +x permission,
# and add nginx to that group.

- name: Create group to enter docker volumes directory
  group:
    name: enter-docker-volumes
    state: present

- name: Ensure nginx user can enter docker volumes
  user:
    name: nginx
    groups: enter-docker-volumes
    append: yes

- name: Ensure user group can enter docker volumes directory
  file:
    path: "{{ item }}"
    state: directory
    group: enter-docker-volumes
    mode: g=x
  loop: 
    - /var/lib/docker/volumes/openzaak-private-media
    - /var/lib/docker/volumes/